install:
    bun install

dev:
    bun --cwd docs dev

build:
    bun run build

build-all:
    build-wasm
    build

dict_path := env("DICT_PATH", "assets/tech.txt")

build-wasm:
    #!/usr/bin/env bash
    export PATH="$HOME/.cargo/bin:$PATH"
    cp "{{ dict_path }}" engine/tech.txt
    cargo build --release --target wasm32-unknown-unknown
    mkdir -p web_packages/wasm/dist
    cp engine/dist/wasm32-unknown-unknown/release/autocorrect.wasm web_packages/wasm/dist/autocorrect.wasm

JAVA_HOME_21 := "/opt/homebrew/opt/openjdk@21"
ANDROID_SDK := "/opt/homebrew/share/android-commandlinetools"

build-android:
    #!/usr/bin/env bash
    set -euo pipefail
    export PATH="$HOME/.cargo/bin:$PATH"
    export JAVA_HOME="{{ JAVA_HOME_21 }}"
    export ANDROID_HOME="{{ ANDROID_SDK }}"
    cp "{{ dict_path }}" engine/tech.txt
    targets=("aarch64-linux-android" "armv7-linux-androideabi" "x86_64-linux-android" "i686-linux-android")
    for t in "${targets[@]}"; do
        echo "Building for $t..."
        cargo build --release --target "$t" --features jni
    done
    dest="web_packages/android/library/src/main/jniLibs"
    mkdir -p "$dest/arm64-v8a" "$dest/armeabi-v7a" "$dest/x86_64" "$dest/x86"
    cp engine/dist/aarch64-linux-android/release/libautocorrect.so "$dest/arm64-v8a/"
    cp engine/dist/armv7-linux-androideabi/release/libautocorrect.so "$dest/armeabi-v7a/"
    cp engine/dist/x86_64-linux-android/release/libautocorrect.so "$dest/x86_64/"
    cp engine/dist/i686-linux-android/release/libautocorrect.so "$dest/x86/"
    echo "Building Android AAR..."
    (cd web_packages/android && ./gradlew build)

build-ios:
    #!/usr/bin/env bash
    export PATH="$HOME/.cargo/bin:$PATH"
    cp "{{ dict_path }}" engine/tech.txt
    cargo build --release --target aarch64-apple-ios
    cargo build --release --target aarch64-apple-ios-sim
    mkdir -p web_packages/swift/Binaries
    cp engine/dist/aarch64-apple-ios/release/libautocorrect.a web_packages/swift/Binaries/
    cp engine/dist/aarch64-apple-ios-sim/release/libautocorrect.a web_packages/swift/Binaries/

build-flutter:
    #!/usr/bin/env bash
    set -euo pipefail
    export PATH="$HOME/.cargo/bin:$PATH"
    cp "{{ dict_path }}" engine/tech.txt
    echo "Copying Dart source from web_packages..."
    cp web_packages/flutter/flutter_autocorrect.dart web_packages/flutter/lib/domain_autocorrect.dart
    echo "Building Flutter targets (C FFI, no JNI)..."
    cargo build --release --target aarch64-linux-android
    cargo build --release --target armv7-linux-androideabi
    cargo build --release --target x86_64-linux-android
    cargo build --release --target i686-linux-android
    cargo build --release --target aarch64-apple-ios
    cargo build --release --target aarch64-apple-ios-sim
    echo "Copying Android .so files..."
    dest_android="web_packages/flutter/android/src/main/jniLibs"
    mkdir -p "$dest_android/arm64-v8a" "$dest_android/armeabi-v7a" "$dest_android/x86_64" "$dest_android/x86"
    cp engine/dist/aarch64-linux-android/release/libautocorrect.so "$dest_android/arm64-v8a/"
    cp engine/dist/armv7-linux-androideabi/release/libautocorrect.so "$dest_android/armeabi-v7a/"
    cp engine/dist/x86_64-linux-android/release/libautocorrect.so "$dest_android/x86_64/"
    cp engine/dist/i686-linux-android/release/libautocorrect.so "$dest_android/x86/"
    echo "Copying iOS .a files..."
    cp engine/dist/aarch64-apple-ios/release/libautocorrect.a web_packages/flutter/ios/
    cp engine/dist/aarch64-apple-ios-sim/release/libautocorrect.a web_packages/flutter/ios/
    echo "Flutter build complete."

build-all-native: build-android build-ios build-flutter

docs-dev:
    bun --cwd docs dev

docs-build:
    bun --cwd docs build

docs-preview:
    bun --cwd docs preview

clean:
    rm -rf web_packages/wasm/dist web_packages/react/dist web_packages/solid/dist docs/dist engine/dist
    rm -rf web_packages/android/build web_packages/android/library/build web_packages/android/.gradle
    rm -rf web_packages/flutter/android/src/main/jniLibs/{arm64-v8a,armeabi-v7a,x86_64,x86}/libautocorrect.so
    rm -rf web_packages/flutter/ios/libautocorrect.a
    rm -f web_packages/flutter/lib/domain_autocorrect.dart
    printf '// Generated by `just build-flutter` -- do not edit.\n// Source: web_packages/flutter/flutter_autocorrect.dart\n' > web_packages/flutter/lib/domain_autocorrect.dart
